In [2]:
import pandas as pd
df = pd.read_csv("../data/stock.csv")

In [3]:
df.head()

         Date      Close       High        Low       Open     Volume
0  2020-01-02  72.333878  72.394086  71.091184  71.344054  135480400
1  2020-01-03  71.630638  72.389257  71.406666  71.563205  146322800
2  2020-01-06  72.201408  72.239942  70.503546  70.754014  118387200
3  2020-01-07  71.861832  72.466315  71.642674  72.211033  108872000
4  2020-01-08  73.017815  73.318854  71.565599  71.565599  132079200

In [4]:
df.shape

(1258, 6)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1258 non-null   str
 1   Close   1258 non-null   float64
 2   High    1258 non-null   float64
 3   Low     1258 non-null   float64
 4   Open    1258 non-null   float64
 5   Volume  1258 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 59.1 KB

In [6]:
df.describe()

             Close         High          Low         Open        Volume
count  1258.000000  1258.000000  1258.000000  1258.000000  1.258000e+03
mean    151.377786   152.899566   149.680871   151.223470  9.057103e+07
std      41.851999    41.992363    41.629303    41.795805  5.324438e+07
min      54.163708    55.160705    51.324804    55.059316  2.323470e+07
25%     126.279119   127.397077   124.278508   125.724360  5.546825e+07
50%     149.968613   151.709757   148.037172   149.788890  7.628335e+07
75%     175.902031   177.452409   174.337230   175.708215  1.077425e+08
max     257.375549   258.448710   255.994390   256.550832  4.265100e+08

In [7]:
df.columns

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [8]:
df.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
import pandas as pd

In [11]:
df=pd.read_csv("../data/stock.csv")
df.head()

         Date      Close       High        Low       Open     Volume
0  2020-01-02  72.333878  72.394086  71.091184  71.344054  135480400
1  2020-01-03  71.630638  72.389257  71.406666  71.563205  146322800
2  2020-01-06  72.201408  72.239942  70.503546  70.754014  118387200
3  2020-01-07  71.861832  72.466315  71.642674  72.211033  108872000
4  2020-01-08  73.017815  73.318854  71.565599  71.565599  132079200

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1258 non-null   str
 1   Close   1258 non-null   float64
 2   High    1258 non-null   float64
 3   Low     1258 non-null   float64
 4   Open    1258 non-null   float64
 5   Volume  1258 non-null   int64
dtypes: float64(4), int64(1), str(1)
memory usage: 59.1 KB

In [13]:
df["Date"]=pd.to_datetime(df["Date"])

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1258 non-null   datetime64[us]
 1   Close   1258 non-null   float64
 2   High    1258 non-null   float64
 3   Low     1258 non-null   float64
 4   Open    1258 non-null   float64
 5   Volume  1258 non-null   int64
dtypes: datetime64[us](1), float64(4), int64(1)
memory usage: 59.1 KB

In [15]:
df.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.shape

(1258, 6)

In [19]:
df.to_csv("../data/clean_stock.csv",index=False)

In [20]:
df.describe()

,Date,Close,High,Low,Open,Volume
count,1258,1258.000000,1258.000000,1258.000000,1258.000000,1.258000e+03
mean,2022-07-01 15:39:46.645469,151.377786,152.899566,149.680871,151.223470,9.057103e+07
min,2020-01-02 00:00:00,54.163708,55.160705,51.324804,55.059316,2.323470e+07
25%,2021-04-02 00:00:00,126.279119,127.397077,124.278508,125.724360,5.546825e+07
50%,2022-06-30 12:00:00,149.968613,151.709757,148.037172,149.788890,7.628335e+07
75%,2023-10-01 06:00:00,175.902031,177.452409,174.337230,175.708215,1.077425e+08
max,2024-12-31 00:00:00,257.375549,258.448710,255.994390,256.550832,4.265100e+08
std,NaN,41.851999,41.992363,41.629303,41.795805,5.324438e+07

In [21]:
import pandas as pd
df=pd.read_csv("../data/clean_stock.csv")
df["Date"]=pd.to_datetime(df["Date"])

In [22]:
df.shape

(1258, 6)

In [23]:
df.describe()

,Date,Close,High,Low,Open,Volume
count,1258,1258.000000,1258.000000,1258.000000,1258.000000,1.258000e+03
mean,2022-07-01 15:39:46.645469,151.377786,152.899566,149.680871,151.223470,9.057103e+07
min,2020-01-02 00:00:00,54.163708,55.160705,51.324804,55.059316,2.323470e+07
25%,2021-04-02 00:00:00,126.279119,127.397077,124.278508,125.724360,5.546825e+07
50%,2022-06-30 12:00:00,149.968613,151.709757,148.037172,149.788890,7.628335e+07
75%,2023-10-01 06:00:00,175.902031,177.452409,174.337230,175.708215,1.077425e+08
max,2024-12-31 00:00:00,257.375549,258.448710,255.994390,256.550832,4.265100e+08
std,NaN,41.851999,41.992363,41.629303,41.795805,5.324438e+07

In [25]:
df.dtypes

Date      datetime64[us]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object

In [27]:
print(df["Date"].min())
print(df["Date"].max())

2020-01-02 00:00:00
2024-12-31 00:00:00

In [29]:
df["Close"].max()

np.float64(257.37554931640625)

In [30]:
df["Close"].min()

np.float64(54.1637077331543)

In [31]:
df["Volume"].mean()

np.float64(90571034.6581876)

In [33]:
df.loc[df["Close"].idxmax()]

Date      2024-12-26 00:00:00
Close              257.375549
High                258.44871
Low                 255.99439
Open               256.550832
Volume               27237100
Name: 1254, dtype: object

In [34]:
df.loc[df["Volume"].idxmax()]

Date      2020-02-28 00:00:00
Close               65.990067
High                67.209159
Low                 61.888623
Open                62.103476
Volume              426510000
Name: 39, dtype: object

In [37]:
df.loc[1,"Close"]

np.float64(71.6306381225586)

In [39]:
df.loc[df["Close"]>150]

           Date       Close        High         Low        Open    Volume
422  2021-09-03  150.629547  150.951699  149.448324  150.102384  57808700
423  2021-09-07  152.962708  153.519141  150.717416  151.283621  82278300
424  2021-09-08  151.420303  153.304386  150.317179  153.245816  74420200
425  2021-09-09  150.405045  152.396511  150.287889  151.791264  57305700
474  2021-11-17  150.057510  151.533737  147.613418  147.623189  88807000
...         ...         ...         ...         ...         ...       ...
1253 2024-12-24  256.560822  256.570737  253.669277  253.868019  23234700
1254 2024-12-26  257.375549  258.448710  255.994390  256.550832  27237100
1255 2024-12-27  253.967392  257.057664  251.453455  256.193162  42355300
1256 2024-12-30  250.598907  251.890657  249.158116  250.628716  35557500
1257 2024-12-31  248.830231  251.672075  247.846510  250.837411  39480700

[628 rows x 6 columns]

In [40]:
df.loc[df["Volume"]>200000000,["Date","Close"]]

           Date       Close
18   2020-01-29   78.111435
35   2020-02-24   71.981689
36   2020-02-25   69.543541
38   2020-02-27   66.028671
39   2020-02-28   65.990067
40   2020-03-02   72.133812
41   2020-03-03   69.842850
42   2020-03-04   73.082481
44   2020-03-06   69.772865
45   2020-03-09   64.254379
46   2020-03-10   68.882072
47   2020-03-11   66.489769
48   2020-03-12   59.923592
49   2020-03-13   67.102936
50   2020-03-16   58.470348
51   2020-03-17   61.041298
52   2020-03-18   59.547009
53   2020-03-19   59.090752
54   2020-03-20   55.339344
55   2020-03-23   54.163708
56   2020-03-24   59.597687
57   2020-03-25   59.269382
58   2020-03-26   62.388336
59   2020-03-27   59.805309
65   2020-04-06   63.361187
66   2020-04-07   62.627319
73   2020-04-17   68.268898
83   2020-05-01   69.782509
91   2020-05-13   74.468826
111  2020-06-11   81.306946
112  2020-06-12   82.008911
117  2020-06-19   84.652168
119  2020-06-23   88.721146
122  2020-06-26   85.598610
146  2020-07-31  102.883888
147  2020-08-03  105.476334
150  2020-08-06  110.283592
152  2020-08-10  109.342705
155  2020-08-13  111.556686
161  2020-08-21  120.635628
162  2020-08-24  122.078453
163  2020-08-25  121.076965
167  2020-08-31  125.165405
169  2020-09-02  127.454567
170  2020-09-03  117.250397
171  2020-09-04  117.327988
172  2020-09-08  109.432426
180  2020-09-18  103.631981
196  2020-10-12  120.664703
197  2020-10-13  117.463799
1124 2024-06-21  205.708069
1187 2024-09-20  226.502090

In [41]:
df.loc[9,["Date","Volume"]]

Date      2020-01-15 00:00:00
Volume              121923600
Name: 9, dtype: object

In [42]:
df.loc[24,"Open"]

np.float64(77.68516086755363)

In [44]:
df.loc[99,["Date","Open","Close"]]

Date     2020-05-26 00:00:00
Open                78.30541
Close              76.666687
Name: 99, dtype: object

In [45]:
df.loc[df["Close"]>150]

           Date       Close        High         Low        Open    Volume
422  2021-09-03  150.629547  150.951699  149.448324  150.102384  57808700
423  2021-09-07  152.962708  153.519141  150.717416  151.283621  82278300
424  2021-09-08  151.420303  153.304386  150.317179  153.245816  74420200
425  2021-09-09  150.405045  152.396511  150.287889  151.791264  57305700
474  2021-11-17  150.057510  151.533737  147.613418  147.623189  88807000
...         ...         ...         ...         ...         ...       ...
1253 2024-12-24  256.560822  256.570737  253.669277  253.868019  23234700
1254 2024-12-26  257.375549  258.448710  255.994390  256.550832  27237100
1255 2024-12-27  253.967392  257.057664  251.453455  256.193162  42355300
1256 2024-12-30  250.598907  251.890657  249.158116  250.628716  35557500
1257 2024-12-31  248.830231  251.672075  247.846510  250.837411  39480700

[628 rows x 6 columns]

In [46]:
df.loc[df["Close"]>df["Open"]]

           Date       Close        High         Low        Open     Volume
0    2020-01-02   72.333878   72.394086   71.091184   71.344054  135480400
1    2020-01-03   71.630638   72.389257   71.406666   71.563205  146322800
2    2020-01-06   72.201408   72.239942   70.503546   70.754014  118387200
4    2020-01-08   73.017815   73.318854   71.565599   71.565599  132079200
5    2020-01-09   74.568779   74.761442   73.742727   73.993187  170108400
...         ...         ...         ...         ...         ...        ...
1250 2024-12-19  248.204208  250.400185  245.521352  245.928753   60882300
1251 2024-12-20  252.874390  253.381146  244.130253  246.465325  147495300
1252 2024-12-23  253.649445  254.027022  251.840991  253.152619   40858800
1253 2024-12-24  256.560822  256.570737  253.669277  253.868019   23234700
1254 2024-12-26  257.375549  258.448710  255.994390  256.550832   27237100

[685 rows x 6 columns]

In [47]:
df.loc[df['Volume']>150000000,["Date","Close"]]

           Date       Close
5    2020-01-09   74.568779
8    2020-01-14   75.303329
16   2020-01-27   74.405037
17   2020-01-28   76.509903
18   2020-01-29   78.111435
...         ...         ...
1091 2024-05-03  181.558868
1117 2024-06-11  205.370987
1118 2024-06-12  211.240143
1124 2024-06-21  205.708069
1187 2024-09-20  226.502090

[136 rows x 2 columns]

In [48]:
df.loc[df["High"]>200,["Date","High","Close"]]

           Date        High       Close
1117 2024-06-11  205.380911  205.370987
1118 2024-06-12  218.308899  211.240143
1119 2024-06-13  214.888539  212.400101
1120 2024-06-14  213.322107  210.665131
1121 2024-06-17  217.069637  214.809219
...         ...         ...         ...
1253 2024-12-24  256.570737  256.560822
1254 2024-12-26  258.448710  257.375549
1255 2024-12-27  257.057664  253.967392
1256 2024-12-30  251.890657  250.598907
1257 2024-12-31  251.672075  248.830231

[141 rows x 3 columns]

In [49]:
df.sort_values(by="Close")

           Date       Close        High         Low        Open     Volume
55   2020-03-23   54.163708   55.160705   51.324804   55.059316  336752800
54   2020-03-20   55.339344   60.792649   55.040002   59.670120  401693200
62   2020-04-01   58.156521   60.041882   57.726823   59.505966  176218400
64   2020-04-03   58.277225   59.312845   57.688200   58.612776  129880000
50   2020-03-16   58.470348   62.542821   57.936845   58.407581  322423600
...         ...         ...         ...         ...         ...        ...
1251 2024-12-20  252.874390  253.381146  244.130253  246.465325  147495300
1252 2024-12-23  253.649445  254.027022  251.840991  253.152619   40858800
1255 2024-12-27  253.967392  257.057664  251.453455  256.193162   42355300
1253 2024-12-24  256.560822  256.570737  253.669277  253.868019   23234700
1254 2024-12-26  257.375549  258.448710  255.994390  256.550832   27237100

[1258 rows x 6 columns]

In [50]:
df.sort_values(by="Close",ascending=False)

           Date       Close        High         Low        Open     Volume
1254 2024-12-26  257.375549  258.448710  255.994390  256.550832   27237100
1253 2024-12-24  256.560822  256.570737  253.669277  253.868019   23234700
1255 2024-12-27  253.967392  257.057664  251.453455  256.193162   42355300
1252 2024-12-23  253.649445  254.027022  251.840991  253.152619   40858800
1251 2024-12-20  252.874390  253.381146  244.130253  246.465325  147495300
...         ...         ...         ...         ...         ...        ...
50   2020-03-16   58.470348   62.542821   57.936845   58.407581  322423600
64   2020-04-03   58.277225   59.312845   57.688200   58.612776  129880000
62   2020-04-01   58.156521   60.041882   57.726823   59.505966  176218400
54   2020-03-20   55.339344   60.792649   55.040002   59.670120  401693200
55   2020-03-23   54.163708   55.160705   51.324804   55.059316  336752800

[1258 rows x 6 columns]

In [51]:
df.sort_values(by="Close",ascending=False).head(5)

           Date       Close        High         Low        Open     Volume
1254 2024-12-26  257.375549  258.448710  255.994390  256.550832   27237100
1253 2024-12-24  256.560822  256.570737  253.669277  253.868019   23234700
1255 2024-12-27  253.967392  257.057664  251.453455  256.193162   42355300
1252 2024-12-23  253.649445  254.027022  251.840991  253.152619   40858800
1251 2024-12-20  252.874390  253.381146  244.130253  246.465325  147495300

In [53]:
df.sort_values(by="Volume",ascending=False).head(10)

          Date       Close        High         Low        Open     Volume
39  2020-02-28   65.990067   67.209159   61.888623   62.103476  426510000
48  2020-03-12   59.923592   65.178947   59.868070   61.784814  418474000
54  2020-03-20   55.339344   60.792649   55.040002   59.670120  401693200
146 2020-07-31  102.883888  103.033962   97.621565   99.616119  374336800
49  2020-03-13   67.102936   67.573676   61.063019   63.945381  370732000
162 2020-08-24  122.078453  124.918056  120.216105  124.833175  345937600
40  2020-03-02   72.133812   72.768705   67.042611   68.143411  341397200
161 2020-08-21  120.635628  121.118187  115.669360  115.681482  338054800
55  2020-03-23   54.163708   55.160705   51.324804   55.059316  336752800
171 2020-09-04  117.327988  119.985713  107.560355  116.464712  332607200

In [54]:
df.sort_values(by=["Close","Volume"], ascending=[False,False])

           Date       Close        High         Low        Open     Volume
1254 2024-12-26  257.375549  258.448710  255.994390  256.550832   27237100
1253 2024-12-24  256.560822  256.570737  253.669277  253.868019   23234700
1255 2024-12-27  253.967392  257.057664  251.453455  256.193162   42355300
1252 2024-12-23  253.649445  254.027022  251.840991  253.152619   40858800
1251 2024-12-20  252.874390  253.381146  244.130253  246.465325  147495300
...         ...         ...         ...         ...         ...        ...
50   2020-03-16   58.470348   62.542821   57.936845   58.407581  322423600
64   2020-04-03   58.277225   59.312845   57.688200   58.612776  129880000
62   2020-04-01   58.156521   60.041882   57.726823   59.505966  176218400
54   2020-03-20   55.339344   60.792649   55.040002   59.670120  401693200
55   2020-03-23   54.163708   55.160705   51.324804   55.059316  336752800

[1258 rows x 6 columns]

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display plots inside Jupyter
%matplotlib inline

# Plot style
plt.style.use("ggplot")

ModuleNotFoundError: No module named 'matplotlib'